Models/Renter.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseRentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Renter()
        {
            this.Props = new HashSet<Prop>();
            this.Request_Details = new HashSet<Request_Details>();
            this.Sold_Property = new HashSet<Sold_Property>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public long PhoneNumber { get; set; }
        public long AadharNumber { get; set; }
        public byte[] ProfileImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prop> Props { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request_Details> Request_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sold_Property> Sold_Property { get; set; }
    }
}

Models/Sold_Property.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseRentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sold_Property
    {
        public int Sold_id { get; set; }
        public int property_id { get; set; }
        public int seller_id { get; set; }
        public int customer_id { get; set; }
        public int deposit_amount { get; set; }
        public int rent { get; set; }
        public string date_of_sale { get; set; }
    
        public virtual Prop Prop { get; set; }
        public virtual Renter Renter { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}

Controllers/RenterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HouseRentManagementSystem.Models;
using System.Collections;
using System.Security.Principal;
using System.Data.Entity.Migrations;
using System.Net.Mail;

namespace HouseRentManagementSystem.Controllers
{
    public class RenterController : Controller
    {
        private Database1Entities1 db = new Database1Entities1();
        
       
        // GET: RegisterUsers
        public ActionResult Index()
        {
            
            string Email = User.Identity.Name;
            var obj = db.Renters.FirstOrDefault(e => e.Email.Equals(Email));
            if (obj.ProfileImage != null)
            {
                TempData["userimage"] = Convert.ToBase64String(obj.ProfileImage);
            }
            else
            {
                TempData["userimage"] = null;
            }
            List<Renter> register = new List<Renter>();

            register.Add(obj);

            int SellerID = Convert.ToInt32(Session["SellerID"]);

            return View(register.AsEnumerable());
            
        }
        public ActionResult SoldProperty(int? id)
        {
            //int id = Convert.ToInt32(Session["SellerID"]);
            var props = db.Props.OrderByDescending(e => e.Id).Where(e => e.SellerID == id && e.Availability != "Available");

            return View(props.ToList());
        }
      
        // GET: RegisterUsers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Renter registerUser = db.Renters.Find(id);
            if (registerUser == null)
            {
                return HttpNotFound();
            }
            return View(registerUser);
        }
// GET: RegisterUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Renter registerUser = db.Renters.Find(id);
            if (registerUser == null)
            {
                return HttpNotFound();
            }
            return View(registerUser);
        }
        

        // POST: RegisterUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Email,Password,PhoneNumber,AadharNumber,ProfileImage")] Renter registerUser,HttpPostedFileBase image)
        {
           
           
                if(image!=null)
            {
                registerUser.ProfileImage = new byte[image.ContentLength];
                image.InputStream.Read(registerUser.ProfileImage, 0, image.ContentLength);

            }
            else
            {
                int Id = Convert.ToInt32(Session["SellerID"]);

                var img = db.Renters.Where(m => m.Id == Id).Select(m => m.ProfileImage).FirstOrDefault();
                if (img != null)
                {
                    registerUser.ProfileImage = img;
                }
            }

            if (ModelState.IsValid)
            {
                
               db.Entry(registerUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(registerUser);
        }
        protected override void Dispose(bool disposing)

        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Request(int id)
        {
            Session["propertyid"] = id;
            var customerid = db.Request_Details.Where(m => m.Property_id == id).Select(m=>m.Customer_id);
            var customers = db.Tenants.Where(m => customerid.Contains(m.Id)).ToList();
            return View(customers);
        }
        public ActionResult Confirmation(int cid)
        {
            Session["customerid"] = cid;
            return View();

        }
        [HttpPost]
        public ActionResult Confirmation(Sold_Property sp)
        {
            int deposit = sp.deposit_amount;
            int rent = sp.rent;
            sp.customer_id = (int)Session["customerid"];
            sp.property_id = (int)Session["propertyid"];
            sp.seller_id = (int)Session["SellerID"];
            sp.date_of_sale = DateTime.Now.ToString();
            db.Sold_Property.Add(sp);
           Prop prop= db.Props.Where(e => e.Id == sp.property_id).FirstOrDefault();
            prop.Availability="Not available";
            db.SaveChanges();
            
            int pid = (int)Session["propertyid"];
            int cid = (int)Session["customerid"];
            string cemail = db.Tenants.Where(m => m.Id == cid).Select(m => m.Email).FirstOrDefault();
            var customer = db.Request_Details.Where(m => m.Customer_id == cid && m.Property_id == pid).FirstOrDefault();
            string pname = db.Props.Where(m => m.Id == pid).Select(m => m.PropertyName).FirstOrDefault();
            string paddress = db.Props.Where(m => m.Id == pid).Select(m => m.Address_Line1).FirstOrDefault();
            ConfirmationMail(cemail, pname, paddress,deposit,rent);
            db.Request_Details.Remove(customer);
            db.SaveChanges();
            List<Request_Details> result = db.Request_Details.Where(m => m.Property_id == pid && m.Customer_id != cid).ToList<Request_Details>();
            Prop bd = db.Props.Where(m => m.Id == pid).FirstOrDefault();
            bd.Availability = "Not Available";
            db.SaveChanges();
            if (result != null)
            {
                foreach (Request_Details x in result)
                {
                    string email = db.Tenants.Where(m => m.Id == x.Customer_id).Select(m => m.Email).FirstOrDefault();
                    string propertyname = db.Props.Where(m => m.Id == pid).Select(m => m.PropertyName).FirstOrDefault();
                    string location = db.Props.Where(m => m.Id == pid).Select(m => m.city).FirstOrDefault();
                    RejectionMail(email, propertyname, location);
                    db.Request_Details.Remove(x);
                    db.SaveChanges();
                }
            }

            Session.Remove("propertyid");
            Session.Remove("customerid");
            return RedirectToAction("Index");
        }






        public ActionResult Rejection(int cid)
        {
            
            int pid = (int)Session["propertyid"];
            string cemail = db.Tenants.Where(m => m.Id == cid).Select(m => m.Email).FirstOrDefault();
            var customer = db.Request_Details.Where(m => m.Customer_id == cid && m.Property_id == pid).FirstOrDefault();
            string pname = db.Props.Where(m => m.Id == pid).Select(m => m.PropertyName).FirstOrDefault();
            string location = db.Props.Where(m => m.Id == pid).Select(m => m.city).FirstOrDefault();
            RejectionMail(cemail, pname, location);
            db.Request_Details.Remove(customer);
            db.SaveChanges();
            
            Session.Remove("propertyid");
            Session.Remove("customerid");
            return RedirectToAction("Index");
        }












        public void ConfirmationMail(string emailid, string propertyname, string location,int deposit,int rent)
        {
            MailMessage mailMessage = new MailMessage("jothilakshmijb2000@gmail.com", emailid);
            mailMessage.IsBodyHtml = true;
            mailMessage.Subject = "House Rent - getMyhouse";
            string link = "https://localhost:44313";
            mailMessage.Body = "<html><body><h3> The House that you have requested for " + propertyname + " located at " + location +
                "</h3><p>This property is rented to You and please make the advance payment of &#8377; "+deposit+ " and your house rent will be  &#8377;"+rent+" </p><p style=color:blue;>For further details please contact the Renter.</p><a href=" + link + ">Click Here</a><h2 style=text-align:center>HAPPY HOMING!</h2><img style=float:right src=~/Icons/logo.png></body></html>";
            SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", 587);
            smtpClient.Credentials = new System.Net.NetworkCredential()
            {
                UserName = "jothilakshmijb2000@gmail.com",
                Password = "Jothilakshmi2815"
            };

            smtpClient.EnableSsl = true;
            smtpClient.Send(mailMessage);
        }
        public void RejectionMail(string emailid, string propertyname, string location)
        {
            MailMessage mailMessage = new MailMessage("jothilakshmijb2000@gmail.com", emailid);
            mailMessage.IsBodyHtml = true;
            mailMessage.Subject = "House Rent - getMyhouse";
            string link = "https://localhost:44313";
            mailMessage.Body = "<html><body><h3> The House that you have requested for " + propertyname + " located at " + location +
                "</h3><p>This property is rented to the other customer </p><p style=color:blue;>Do check new houses that suits you.</p><a href=" + link + ">Click Here</a><h2 style=text-align:center>HAPPY HOMING!</h2></body></html>";
            SmtpClient smtpClient = new SmtpClient("smtp.gmail.com", 587);
            smtpClient.Credentials = new System.Net.NetworkCredential()
            {
                UserName = "jothilakshmijb2000@gmail.com",
                Password = "Jothilakshmi2815"
            };

            smtpClient.EnableSsl = true;
            smtpClient.Send(mailMessage);
        }
    }
}

Views/Renter/Confirmation.cshtml
@model HouseRentManagementSystem.Models.Sold_Property

@{
    ViewBag.Title = "Confirmation";

}

<h2 style="text-align:center">CONFIRMATION TO RENT A PROPERTY</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" align="center">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            <label class="col-sm-10">Advance Payment</label>
            <div class="row-cols-3">
                @Html.EditorFor(model => model.deposit_amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.deposit_amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="col-sm-9">Rent</label>
            <div class="row-cols-3">
                @Html.EditorFor(model => model.rent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rent, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<button class="btn btn-sm btn-info" id="btn" onclick="location.href = '@Url.Action("Index")'">
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
</button>

Views/Renter/Edit.cshtml
@model HouseRentManagementSystem.Models.Renter

@{
    ViewBag.Title = "Edit";
    Layout = null;
}


<head>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" rel="stylesheet" type="text/css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>


    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-top-fixed/">



    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


</head>
<style>

    #btn {
        left: 20%;
        position: absolute;
    }

    .logo {
        position: fixed;
        bottom: 0;
        right: 0;
        width: 100px;
        height: 100px;
    }

    button {
        position: relative;
    }


    .img-wrap {
        position: relative;
        display: inline-block;
        font-size: 0;
    }

        .img-wrap #edit {
            position: absolute;
            top: 1px;
            right: 1px;
            z-index: 100;
            padding: 12px;
            color: black;
            font-weight: bolder;
            cursor: pointer;
            opacity: .2;
            text-align: center;
            font-size: 35px;
            line-height: 10px;
            border-radius: 50%;
            opacity: 2;
        }

        .img-wrap:hover #edit {
            opacity: 1;
        }


    .panel-body {
        text-align: center;
        justify-content: center;
    }

    .form-horizontal {
        margin: auto;
        width: 45%;
    }


    h3 {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    .scroller {
        height: 500px;
        overflow-y: auto;
        overflow-x: hidden;
    }


    #image1 {
        cursor: pointer;
        width: 100px;
        height: 100px;
        border: 2px solid #03b1ce;
    }
</style>
<body>
    @using (Html.BeginForm("Edit", "Renter", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        //string image = Convert.ToString(Session["Image"]);
        <div class="panel-body">

            <div class="box box-info">

                <div class="box-body">
                    <div class="col-sm-6">
                        <div class="userimage">
                            @if (Session["base64"] != null)
                            {

                                //TempData["userimage"] = Convert.ToBase64String(obj.ProfileImage);

                                var base64 = Session["base64"];

                                var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);



                                <div class="img-wrap" style="text-align:right">
                                    <input id="image" name="image" class="hidden" type="file" hidden>

                                    <span id="edit">&#43;</span>
                                    <img src="@imgsrc" style="height:120px; width:120px;" class="rounded-circle" id="image1">

                                </div>

                            }
                            else
                            {
                                <div class="img-wrap" style="text-align:right">
                                    <input id="image" name="image" class="hidden" type="file" hidden>
                                    <span id="edit">&#43;</span>
                                    <img alt="User Pic" style="height:120px; width:120px;" src="~/Icons/avatar.png" id="image1" class="rounded-circle">
                                </div>


                            }

                            <!--
                            <img alt="User Pic" src="https://x1.xingassets.com/assets/frontend_minified/img/users/nobody_m.original.jpg" id="profile-image1" class="rounded-circle">

                            <input id="profile-image-upload" class="hidden" type="file">
                            <div style="color:#999;">click here to change profile image</div>
                                -->
                            <!--Upload Image Js And Css-->







                        </div>

                        <br>

                        <!-- /input-group -->
                    </div> <br><br><h2 style="text-align:left;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">   <i class="far fa-edit" id="edit"></i>EDIT MY PROFILE</h2>
                </div>
            </div>
        </div>

        <div class="form-horizontal" align="center">

            <div class="scroller">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    <label class="col-md-4">First name</label>
                    <div class="row-cols-2">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4">Last name</label>
                    <div class="row-cols-2">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">

                    <label class="col-md-4">Email</label>
                    <div class="row-cols-2">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4">Password</label>
                    <div class="row-cols-2">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4">Phone number</label>
                    <div class="row-cols-2">
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4">Aadhar number</label>
                    <div class="row-cols-2">
                        @Html.EditorFor(model => model.AadharNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AadharNumber, "", new { @class = "text-danger" })
                    </div>
                </div>


                <br>
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Save changes" class="btn btn-default" />
                    </div>
                </div>
                <button class="btn btn-sm btn-info" id="btn" onclick="location.href = '@Url.Action("Index")'">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    Back
                </button>
            </div>
        </div>
        <script>
            $(function () {
                $('#image1').on('click', function () {
                    $('#image').click();
                });
            });</script>


    }     <img src="~/Icons/logo.png" class="logo" />


</body>

Views/Renter/Index.cshtml
@model IEnumerable<HouseRentManagementSystem.Models.Renter>

@{
    ViewBag.Title = "Index";
    Layout = null;

}  
<br>


<head>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>



    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" rel="stylesheet" type="text/css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-top-fixed/">



    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <style>
        .logo {
            position: fixed;
            bottom: 0;
            right: 0;
            width: 100px;
            height: 100px;
        }

        .styled-table {
            width: 50%;
            margin-left: 15%;
            margin-right: 15%;
            border-collapse: collapse;
            margin: 25px 0;
            font-family: sans-serif;
            min-width: 400px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
        }

        .btn {
            left: 20%;
            position: absolute;
        }

        .styled-table {
            margin: 0 auto;
        }

            .styled-table th {
                background-color: #37474f;
                color: #ffffff;
                text-align: left;
            }

            .styled-table td {
                background-color: white;
                color: black;
                text-align: left;
            }

            .styled-table th,
            .styled-table td {
                padding: 12px 15px;
            }

            .styled-table tbody tr {
                border-bottom: 1px solid chartreuse;
            }

                .styled-table tbody tr:nth-of-type(even) {
                    background-color: chartreuse;
                }

                .styled-table tbody tr:last-of-type {
                    border-bottom: 1px solid chartreuse;
                }

                .styled-table tbody tr.active-row {
                    font-weight: bold;
                    color: #009879;
                }

        table {
            border: 4px solid chartreuse;
        }
    </style>
</head>
<h3 style="        text-align: center;
        font-family: Garamond;
        text-decoration: double;
        text-emphasis: dot">
    MY PROFILE
</h3>
<br>
<br>

<table class="styled-table">

    @foreach (var item in Model)
    {
        <tbody>

            <tr>
                <th>
                    First name
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)

                </td>
        </tbody>
        <tbody>

            <tr>
                <th>
                    Last name
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)


                </td>
        </tbody>
        <tbody>

            <tr>
                <th>
                    Email
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
        </tbody>
        <tbody>

            <tr>
                <th>
                    Password
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
        </tbody>
        <tbody>

            <tr>
                <th>
                    Phone number
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
        </tbody>
        <tbody>

            <tr>
                <th>
                    Aadhar number
                </th>
                <td>
                    @Html.DisplayFor(modelItem => item.AadharNumber)
                </td>
        </tbody>
        <tbody>

            <tr>
                <th>
                    Profile Image
                </th>
                <td>
                    @{

                        // if (ViewBag.image != null)
                        if (TempData["userimage"] != null)
                        {

                            <!--<input id="image" name="image" class="hidden" type="file" hidden>-->
                            //TempData["userimage"] = Convert.ToBase64String(obj.ProfileImage);

                            var base64 = TempData["userimage"];

                            var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                            Session["base64"] = base64;

                            <img src="@imgsrc" style="height:150px; width:150px;">

                        }

                        // string base64 = Convert.ToString(Session["Image"]);

                        else
                        {
                            <img src="~/Icons/avatar.png" style="height:150px; width:150px;">

                        }
                    }

                </td>


            </tr>
        </tbody>


    }

</table>
<img src="~/Icons/logo.png" class="logo" />
<br>
<br>
<button class="btn btn-sm btn-info" onclick="location.href = '@Url.Action("Index","Account")'">
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
</button>