Models/Image.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseRentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public byte[] PropertyImage { get; set; }
        public int PropertyId { get; set; }
    
        public virtual Prop Prop { get; set; }
    }
}

Models/PriceRange.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseRentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceRange
    {
        public int PriceID { get; set; }
        public string Price { get; set; }
    }
}

Controllers/AdminPropertyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HouseRentManagementSystem.Models;

namespace HouseRentManagementSystem.Controllers
{
    public class AdminPropertyController : Controller
    {
        private Database1Entities1 db = new Database1Entities1();

        // GET: AdminProperty
        public ActionResult Index()
        {
            var props = db.Props.Include(p => p.Renter);
            return View(props.ToList());
        }

        // GET: AdminProperty/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prop prop = db.Props.Find(id);
            if (prop == null)
            {
                return HttpNotFound();
            }
            return View(prop);
        }

        // GET: AdminProperty/Create
        public ActionResult Create()
        {
            ViewBag.SellerID = new SelectList(db.Renters, "Id", "FirstName");
            return View();
        }

        // POST: AdminProperty/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BHK_type,Id,House_type,Address_Line1,Address_Line2,city,state,Rent,SellerID,Availability,SquareFeet,PropertyName")] Prop prop)
        {
            if (ModelState.IsValid)
            {
                db.Props.Add(prop);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SellerID = new SelectList(db.Renters, "Id", "FirstName", prop.SellerID);
            return View(prop);
        }

        // GET: AdminProperty/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prop prop = db.Props.Find(id);
            if (prop == null)
            {
                return HttpNotFound();
            }
            ViewBag.SellerID = new SelectList(db.Renters, "Id", "FirstName", prop.SellerID);
            return View(prop);
        }

        // POST: AdminProperty/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BHK_type,Id,House_type,Address_Line1,Address_Line2,city,state,Rent,SellerID,Availability,SquareFeet,PropertyName")] Prop prop)
        {
            if (ModelState.IsValid)
            {
                db.Entry(prop).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SellerID = new SelectList(db.Renters, "Id", "FirstName", prop.SellerID);
            return View(prop);
        }

        // GET: AdminProperty/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prop prop = db.Props.Find(id);
            if (prop == null)
            {
                return HttpNotFound();
            }
            return View(prop);
        }

        // POST: AdminProperty/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            List<Image> image = db.Images.Where(m => m.PropertyId == id).ToList();
            foreach (var i in image)
            {
                db.Images.Remove(i);
            }
            Prop prop = db.Props.Find(id);
            db.Props.Remove(prop);
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PropsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HouseRentManagementSystem.Models;
using System.Data.SqlClient;
using System.Data.Entity.Validation;
using System.Text;
using Microsoft.Extensions.Logging;
using System.IO;
using PagedList;
 

namespace HouseRentManagementSystem.Controllers
{
    public class PropsController : Controller
    {
        
        private Database1Entities1 db = new Database1Entities1();

       
        // GET: Props
        public ActionResult Index()
        {
            
            int SellerID = Convert.ToInt32(Session["SellerID"]);
            // return View(db.Props.ToList().Where(e=>e.SellerID== SellerID));         
            int count = db.Props.Count();
           
                        return View(db.Props.Where(e => e.SellerID == SellerID).ToList());

        }
        public JsonResult Autocomplete(string Prefix)
        {
            var property_city = (from p in db.Props
                                 where p.city.StartsWith(Prefix)
                                 select new
                                 {
                                     label = p.city,
                                     val = p.city
                                 }).ToList();
            return Json(property_city);

        }
        public ActionResult Search(string search)
        {
            Session["search"] = search;
            if (Session["min"] != null)
            {
                int min = (int)Session["min"];
                int max = (int)Session["max"];
                List<Prop> property = db.Props.Where(m => m.city == search&& m.Rent>=min &&m.Rent<= max && m.Availability == "Available").ToList<Prop>();
                return View(property);
            }
            else
            {
                List<Prop> property = db.Props.Where(m => m.city == search && m.Availability == "Available").ToList<Prop>();
                return View(property);
            }


        }
        public ActionResult PriceRange(int min,int max)
        {
            Session["min"] = min;
            Session["max"] = max;
            if (min != 25000 && max != 25000)
            {
                if (Session["search"] != null)
                {
                    string city = (string)Session["search"];
                    var result = db.Props.Where(m => m.Rent >= min && m.Rent <= max && m.city == city && m.Availability == "Available").ToList();
                    return View(result);
                }
                else
                {
                    var result = db.Props.Where(m => m.Rent >= min && m.Rent <= max && m.Availability == "Available").ToList();
                    return View(result);
                }
            }
            else
            {
                var result = db.Props.Where(m => m.Rent >= min && m.Availability == "Available").ToList();
                return View(result);
            }
        }
       
        public ActionResult Sort(int price)
        {
            Session["price"] = price;
         
                if (Session["search"] == null && Session["min"] == null && Session["max"] == null)
                {
                    if (price == 1)
                    {
                        var result = db.Props.OrderBy(m => m.Rent).Where(m => m.Availability == "Available").ToList();
                        return View(result);
                    }
                    if (price == 2)
                    {
                        var result = db.Props.OrderByDescending(m => m.Rent).Where(m => m.Availability == "Available").ToList();
                        return View(result);
                    }
                }
                else if (Session["search"] != null && Session["min"] == null && Session["max"] == null)
                {
                    if (price == 1)
                    {
                        string city = (string)Session["search"];
                        var result = db.Props.OrderBy(m => m.Rent).Where(m => m.Availability == "Available" && m.city == city).ToList();
                        return View(result);
                    }
                    if (price == 2)
                    {
                        string city = (string)Session["search"];
                        var result = db.Props.OrderByDescending(m => m.Rent).Where(m => m.Availability == "Available" && m.city == city).ToList();
                        return View(result);
                    }
                }
          else if(Session["search"] == null && Session["min"] != null && Session["max"] != null)
            {
               
                if(price==1)
                {
                    int min = (int)Session["min"];
                    int max = (int)Session["max"];
                    var result = db.Props.OrderBy(m => m.Rent).Where(m => m.Availability == "Available" && m.Rent >= min&& m.Rent<=max).ToList();
                    return View(result);

                }
                if (price == 2)
                {
                    int min = (int)Session["min"];
                    int max = (int)Session["max"];
                    var result = db.Props.OrderByDescending(m => m.Rent).Where(m => m.Availability == "Available" && m.Rent >= min && m.Rent <= max).ToList();
                    return View(result);
                }
            }

            else
            {
                int min = (int)Session["min"];
                int max = (int)Session["min"];
                string city = (string)Session["search"];
                if(price==1)
                {
                    var result = db.Props.OrderBy(m => m.Rent).Where(m => m.Availability == "Available" && m.Rent >= min && m.Rent <= max && m.city==city).ToList();
                    return View(result);

                }
                if (price == 2)
                {
                    var result = db.Props.OrderByDescending(m => m.Rent).Where(m => m.Availability == "Available" && m.Rent >= min && m.Rent <= max && m.city == city).ToList();
                    return View(result);

                }

            }

            return View();
        }
        public ActionResult UserIndex(int? page)
        { 
            var pageNumber = page ?? 1;
                var pageSize = 6;
          


            int uid = Convert.ToInt32(Session["userID"]);
            var result = db.Request_Details.Where(m => m.Customer_id == uid).Select(m => m.Property_id);
      
        var prop = db.Props.Where(m => !result.Contains(m.Id) && m.Availability=="Available");
            var obj = prop.OrderBy(m => m.Id).ToPagedList(pageNumber, pageSize);


            var sellers = from s in db.Sold_Property group s by s.seller_id;
            var topseller = sellers.OrderByDescending(m => m.Count()).Take(3);

            var topsellerid = topseller.Select(m => m.Key);
            var seller = db.Renters.Where(m => topsellerid.Contains(m.Id));
            List<int> count = new List<int>();
            List<Renter> list = new List<Renter>();
            foreach (var item in topsellerid)
            {
                count.Add(db.Sold_Property.Count(m => m.seller_id == item));
            }



            ViewBag.count = count;
            ViewBag.topseller = seller;
            return View(obj);
        }
        [HttpPost]
        public ActionResult UserIndex()
        {
           
            
            return View();
        }
    public ActionResult CustomerRequest()
        {
            int SellerID = Convert.ToInt32(Session["SellerID"]);
            var prop1 = db.Props.Where(e => e.SellerID == SellerID);
            
                if (prop1 != null)
            {
              var  prop = db.Tenants.Where(e => e.Id == SellerID);
                return View(prop.ToList());
            }
            return View();
        }
        public ActionResult UserIndexs(int id,int sid)
        {            
            int uid = Convert.ToInt32(Session["userID"]);

            Request_Details rd = new Request_Details
            {
                Seller_Id = sid,
                Property_id = id,
                Customer_id = uid
            };
            db.Request_Details.Add(rd);
            db.SaveChanges();
            return RedirectToAction("RequestedProperty");
        }
        public ActionResult RequestedProperty()
        {
            int uid = Convert.ToInt32(Session["userID"]);
        var result = db.Request_Details.Where(m => m.Customer_id == uid).Select(m => m.Property_id);
        var prop = db.Props.Where(m => result.Contains(m.Id)).ToList();
            return View(prop);
        }

        public ActionResult Images(int id)
        {
            var prop = db.Props.Where(e => e.Id == id);
            return View(prop.ToList());
        }

        public ActionResult Image(int id)
        {
            var prop = db.Props.Where(e => e.Id == id);
            return View(prop.ToList());
        }
        public ActionResult EditImages(int id)
        {
            Session["prop_id"] = id;
            var prop = db.Props.Where(e => e.Id == id).ToList();
            return View(prop);
        }
        [HttpPost]
        public ActionResult EditImages(HttpPostedFileBase[] image)
        {
            if (image != null)
            {
                foreach (var images in image)
                {

                    BinaryReader br = new BinaryReader(images.InputStream);
                    Image img = new Image
                    {
                        PropertyId = (int)Session["prop_id"],
                        PropertyImage = br.ReadBytes((int)images.ContentLength)
                    };
                    // Prop.Images = new List<Image> { img };
                    db.Images.Add(img);
                }
                db.SaveChanges();
            }

Views/Props/Create.cshtml
@model HouseRentManagementSystem.Models.Prop


<!DOCTYPE html>

@{
    ViewBag.Title = "Create";
}
<style>
    .scroller {
        height: 400px;
        overflow-y: auto;
        overflow-x: hidden;
    }


    .panel-body {
        text-align: center;
        justify-content: center;
    }

    .form-horizontal {
        margin: auto;
        width: 45%;
    }
</style>
<i class="fas fa-home" style="font-size:50px;position:absolute;left:30%"></i>
<h2 style="text-align:center">CREATE NEW PROPERTY</h2>

@using (Html.BeginForm("Create","Props",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="scroller">
        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="col-md-4">Property name</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.PropertyName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PropertyName, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                <label class="col-md-4">BHK type</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.BHK_type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.BHK_type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4">House type</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.House_type, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.House_type, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4">Address line 1</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.Address_Line1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address_Line1, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4">Address line 2</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.Address_Line2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address_Line2, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4">City</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.city, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4">State</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.state, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.state, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4">Rent</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.Rent, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Rent, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4">Images</label>
                <div class="row-cols-2">
                    <input type="file" name="images" id="images" multiple>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4">Square feet</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.SquareFeet, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SquareFeet, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-5" align="right">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>

}

<button class="btn btn-md btn-info" id="btn" onclick="location.href = '@Url.Action("Index","AdminProperty")'">
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
</button>

Views/Props/Delete.cshtml
@model HouseRentManagementSystem.Models.Prop

@{
    ViewBag.Title = "Delete";
    Layout = null;
}

<link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-top-fixed/">

<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/modernizr-2.6.2.js"></script>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" rel="stylesheet" type="text/css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<style>
  
    .logo {
        position: fixed;
        bottom: 0;
        right: 0;
        width: 100px;
        height: 100px;
    }
    button {
        position: relative;
    }

    .styled-table {
        width: 50%;
        margin-left: 15%;
        margin-right: 15%;
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
        border: 6px groove black;
    }

    .styled-table {
        margin: 0 auto;
    }

        .styled-table th {
            background-color: palevioletred;
            color: #ffffff;
            text-align: left;
        }

        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

            .styled-table tbody tr:nth-of-type(even) {
                background-color: #f3f3f3;
            }

            .styled-table tbody tr:last-of-type {
                border-bottom: 2px solid lightpink;
            }

            .styled-table tbody tr.active-row {
                font-weight: bold;
                color: #009879;
            }
          body
            {
                background-image:linear-gradient(white,lightblue);
            }
</style>
<div class="class">
    <h3 style="text-align:center;font-family:'Segoe'">
        PROPERTY DETAILS
    </h3><br>


    <div class="table-responsive-md">
        <button type="button" style="left:64%;position:absolute" class="btn btn-info" data-toggle="modal" data-target="#myModal" onclick="location.href = '@Url.Action("Images", "Props", new { id = Model.Id })'">
            <span class="glyphicon glyphicon-picture"></span> Property images
        </button>
        <br><br>
        <table class="styled-table" align="center">
            <tbody>

                <tr>
                    <th>
                        Property name
                    </th>

                    <td>
                        @Html.DisplayFor(model => model.PropertyName)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        BHK type
                    </th>


                    <td>
                        @Html.DisplayFor(model => model.BHK_type)
                    </td>
            </tbody>


            <tbody>

                <tr>
                    <th>

                        House type
                    </th>


                    <td>
                        @Html.DisplayFor(model => model.House_type)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        Address line 1
                    </th>

                    <td>
                        @Html.DisplayFor(model => model.Address_Line1)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        Address line 2
                    <td>
                        @Html.DisplayFor(model => model.Address_Line2)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        City
                    <td>
                        @Html.DisplayFor(model => model.city)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        State
                    </th>

                    <td>
                        @Html.DisplayFor(model => model.state)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        Rent
                    </th>

                    <td>
                        @Html.DisplayFor(model => model.Rent)
                    </td>


                </tr>
            </tbody>

        </table>

    </div>

  <br>
  
        <button class="btn btn-sm btn-info" onclick="location.href = '@Url.Action("Index","Props")'">
            <span class="glyphicon glyphicon-chevron-left"></span>
            Back
        </button>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">

                <input type="submit" style="left:50%;position:absolute" value="Delete" class="btn btn-sm btn-danger" /> 

            </div>
        }

    <img src="~/Icons/logo.png" class="logo" />


</div>

Views/Props/EditImages.cshtml
@model IEnumerable<HouseRentManagementSystem.Models.Prop>

@{
    ViewBag.Title = "EditImages";
    Layout = null;
}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" rel="stylesheet" type="text/css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/modernizr-2.6.2.js"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-top-fixed/">



<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<style>

    #close {
        z-index: 5;
    }

    .img-wrap {
        position: relative;
        display: inline-block;
        border: 1px red solid;
        font-size: 0;
    }

        .img-wrap .close {
            position: absolute;
            top: 2px;
            right: 2px;
            z-index: 100;
            background-color: #FFF;
            padding: 5px 2px 2px;
            color: #000;
            font-weight: bold;
            cursor: pointer;
            opacity: .2;
            text-align: center;
            font-size: 22px;
            line-height: 10px;
            border-radius: 50%;
            opacity: 2;
        }

        .img-wrap:hover .close {
            opacity: 1;
        }
</style>
@using (Html.BeginForm("EditImages", "Props", FormMethod.Post, new { enctype = "multipart/form-data" }))

{

    <div class="form-group">

        <div class="col-sm">
            <input type="button" class="btn-info" id="image1" value="Add new images">
            <input type="file" class="hidden" name="image" id="image" multiple>
        </div>

    </div>

    <div class="form-group">


        <div class="col-md-offset-2 col-md-10">

            <h4>
                Click here to save added image(s)

                <input type="submit" value=" Save " class="btn btn-dark" />
            </h4>
        </div>

    </div>
}
<script>
    $(function () {
        $('#image1').on('click', function () {
            $('#image').click();
        });
    });</script>

@foreach (var item in Model)
{

    var image = item.Images1;
    if (image.Count > 0)
    {


        for (int i = 0; i < image.Count; i++)
        {

            var base64 = Convert.ToBase64String(image[i].PropertyImage);
            var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
            <div class="img-wrap">
                <span class="close" onclick="location.href = '@Url.Action("RemoveImages", "Props", new {id=image[i].Id })'">&times;</span>
                <img src="@imgsrc" style="width:150px; height:150px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </div>

        }


    }
    <br><br><br>
    <div class="col-10">

        <button type="button" class="btn btn-info" onclick="location.href = '@Url.Action("Edit", "Props", new { id = item.Id })'">
            Back
        </button>
    </div>
}