Controllers/AdminRenterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HouseRentManagementSystem.Models;

namespace HouseRentManagementSystem.Views.AdminRenter
{
    public class AdminRenterController : Controller
    {
        private Database1Entities1 db = new Database1Entities1();

        // GET: AdminRenter
        public ActionResult Index()
        {
            return View(db.Renters.ToList());
        }

        // GET: AdminRenter/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Renter Renter = db.Renters.Find(id);
            if (Renter == null)
            {
                return HttpNotFound();
            }
            return View(Renter);
        }

        // GET: AdminRenter/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminRenter/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,Email,Password,PhoneNumber,AadharNumber")] Renter Renter)
        {
            if (ModelState.IsValid)
            {
                db.Renters.Add(Renter);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(Renter);
        }

        // GET: AdminRenter/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Renter Renter = db.Renters.Find(id);
            if (Renter == null)
            {
                return HttpNotFound();
            }
            return View(Renter);
        }

        // POST: AdminRenter/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,Email,Password,PhoneNumber,AadharNumber")] Renter Renter)
        {
            if (ModelState.IsValid)
            {
                db.Entry(Renter).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Renter);
        }

        // GET: AdminRenter/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Renter Renter = db.Renters.Find(id);
            if (Renter == null)
            {
                return HttpNotFound();
            }
            return View(Renter);
        }

        // POST: AdminRenter/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
           
              List<Prop> propid = db.Props.Where(e => e.SellerID == id).ToList();
                foreach (var i in propid)
                {

                    List<Image> image = db.Images.Where(m => m.PropertyId == i.Id).ToList();
                    foreach (var j in image)
                    {
                        db.Images.Remove(j);
                        db.Props.Remove(i);
                    }

                }
                Renter renter = db.Renters.Find(id);
                db.Renters.Remove(renter);
                
            
           
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/AdminRenter/Create.cshtml
@model HouseRentManagementSystem.Models.Renter


<!DOCTYPE html>

@{
    ViewBag.Title = "Create";
}
<style>
    .scroller {
        height: 400px;
        overflow-y: auto;
        overflow-x: hidden;
    }


    .panel-body {
        text-align: center;
        justify-content: center;
    }

    .form-horizontal {
        margin: auto;
        width: 45%;
    }
</style>
<i class="fas fa-user-plus" style="font-size:50px;position:absolute;left:28%"></i>
<h2 style="text-align:center">CREATE NEW USER (RENTER)</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="scroller">
        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="col-md-4">First name</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                <label class="col-md-4">Last name</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4">Email</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4">Password</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4">Phone number</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4">Aadhar number</label>
                <div class="row-cols-2">
                    @Html.EditorFor(model => model.AadharNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AadharNumber, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-5" align="right">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>

}

<button class="btn btn-md btn-info" id="btn" onclick="location.href = '@Url.Action("Index","AdminRenter")'">
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
</button>

Views/AdminRenter/Delete.cshtml
@model HouseRentManagementSystem.Models.Renter

@{
    ViewBag.Title = "Delete";
    Layout = null;
}

<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" rel="stylesheet" type="text/css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>ViewBag.Title - My ASP.NET Application</title>
<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/modernizr-2.6.2.js"></script>


<link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-top-fixed/">



<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<style>

    .logo {
        position: fixed;
        bottom: 0;
        right: 0;
        width: 100px;
        height: 100px;
    }

    button {
        position: relative;
    }

    .styled-table {
        width: 50%;
        margin-left: 15%;
        margin-right: 15%;
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
        border: 6px groove outset;
    }

    #edit {
        z-index: 5;
    }

    .styled-table {
        margin: 0 auto;
    }

        .styled-table th {
            background-color: palevioletred;
            color: #ffffff;
            text-align: left;
        }

        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

            .styled-table tbody tr:nth-of-type(even) {
                background-color: #f3f3f3;
            }

            .styled-table tbody tr:last-of-type {
                border-bottom: 2px solid hidden;
            }

            .styled-table tbody tr.active-row {
                font-weight: bold;
                color: #009879;
            }

    body {
        background-image: linear-gradient(palered,white);
    }
</style>
<div class="class">
    <h3 style="text-align:center;font-family:'Segoe'">
        USER DETAILS (RENTER)
    </h3><br>

    <h2 style="text-align:center;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">
        <i class="fa fa-trash" style="font-size:50px"></i>&nbsp;DELETE PROFILE
    </h2>



    <div class="table-responsive-md">

        <br><br>
        <table class="styled-table" align="center">
            <tbody>

                <tr>
                    <th>
                        First name
                    </th>

                    <td>
                        @Html.DisplayFor(model => model.FirstName)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        Last name
                    </th>


                    <td>
                        @Html.DisplayFor(model => model.LastName)
                    </td>
            </tbody>


            <tbody>

                <tr>
                    <th>

                        Email
                    </th>


                    <td>
                        @Html.DisplayFor(model => model.Email)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        Password
                    </th>

                    <td>
                        @Html.DisplayFor(model => model.Password)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        Phone number
                    <td>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        Aadhar number
                    <td>
                        @Html.DisplayFor(model => model.AadharNumber)
                    </td>
            </tbody>

        </table>

    </div>

    <br> <br>

    <button style="right:70%;position:absolute" class="btn btn-sm btn-info" onclick="location.href = '@Url.Action("Index","AdminRenter")'">
        <span class="glyphicon glyphicon-chevron-left"></span>
        Back
    </button>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">

            <input type="submit" style="left:50%;position:absolute" value="DELETE" class="btn btn-sm btn-danger" />

        </div>
    }

    <img src="~/Icons/logo.png" class="logo" />


</div>

Views/AdminRenter/Details.cshtml
@model HouseRentManagementSystem.Models.Renter

@{
    ViewBag.Title = "Details";
    Layout = null;

}
<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/modernizr-2.6.2.js"></script>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" rel="stylesheet" type="text/css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>

<link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-top-fixed/">



<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<style>
    .logo {
        position: fixed;
        bottom: 0;
        right: 0;
        width: 100px;
        height: 100px;
    }

    #img {
        left: 64%;
        position: absolute;
    }

    .btn {
        left: 20%;
        position: absolute;
    }

    .styled-table {
        width: 50%;
        margin-left: 15%;
        margin-right: 15%;
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

    .styled-table {
        margin: 0 auto;
        border: 2PX double;
    }

        .styled-table th {
            background-color: lightgreen;
            color: black;
            text-align: left;
        }

        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

            .styled-table tbody tr:nth-of-type(even) {
                background-color: black;
            }

            .styled-table tbody tr:last-of-type {
                border-bottom: 2px solid black;
            }

            .styled-table tbody tr.active-row {
                font-weight: bold;
                color: #009879;
            }
</style>
<div>
    <h3 style="text-align:center">
        USER DETAILS (RENTER)
    </h3>
    <hr />

    <div class="table-responsive-md">
        &emsp;&emsp;&emsp;

        <br><br />
        <table class="styled-table" align="center">
            <tbody>

                <tr>
                    <th>
                        First name
                    </th>

                    <td>
                        @Html.DisplayFor(model => model.FirstName)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        Last name
                    </th>


                    <td>
                        @Html.DisplayFor(model => model.LastName)
                    </td>
            </tbody>


            <tbody>

                <tr>
                    <th>

                        Email
                    </th>


                    <td>
                        @Html.DisplayFor(model => model.Email)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        Password
                    </th>

                    <td>
                        @Html.DisplayFor(model => model.Password)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        Phone number
                    <td>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </td>
            </tbody>
            <tbody>

                <tr>
                    <th>
                        Aadhar number
                    <td>
                        @Html.DisplayFor(model => model.AadharNumber)
                    </td>
            </tbody>
            <tbody>
            </tbody>

        </table>

    </div>

</div>
<br>
<br>

<img src="~/Icons/logo.png" class="logo" />

<button class="btn btn-md btn-info" onclick="location.href = '@Url.Action("Index","AdminRenter")'">
    <span class="glyphicon glyphicon-chevron-left"></span>
    Back
</button>

Views/AdminRenter/Edit.cshtml
@model HouseRentManagementSystem.Models.Renter

 @{   Layout = null;
}


<head>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" rel="stylesheet" type="text/css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>


    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/navbar-top-fixed/">



    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


</head>
<style>
   

    .logo {
        position: fixed;
        bottom: 0;
        right: 0;
        width: 100px;
        height: 100px;
    }
    button {
        position: relative;
    }
    #edit {
        z-index: 5;
    }

    .img-wrap {
        position: relative;
        display: inline-block;
        font-size: 0;
    }

        .img-wrap #edit {
            position: absolute;
            top: 1px;
            right: 1px;
            z-index: 100;
            padding: 8px;
            color: white;
            font-weight: bolder;
            cursor: pointer;
            opacity: .2;
            text-align: center;
            font-size: 35px;
            line-height: 10px;
            border-radius: 50%;
            opacity: 2;
        }

        .img-wrap:hover #edit {
            opacity: 1;
        }

   

   

    .panel-body {
        text-align: center;
        justify-content: center;
    }

    .form-horizontal {
        margin: auto;
        width: 45%;
    }


    h3 {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
  
    .scroller {
        height: 500px;
        overflow-y: auto;
        overflow-x: hidden;
    }


    #image1 {
        cursor: pointer;
        width: 100px;
        height: 100px;
        border: 2px solid #03b1ce;
    }

    #btn {
        left: 20%;
        position: absolute;
    }

</style>
<body>
    @using (Html.BeginForm("Edit", "AdminRenter", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

 <br><br><h2 style="text-align:center;font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif">   <i class="far fa-edit" id="edit"></i>EDIT PROFILE</h2>
             
        <div class="form-horizontal" align="center">

            <div class="scroller">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    <label class="col-md-4">First name</label>
                    <div class="row-cols-2">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4">Last name</label>
                    <div class="row-cols-2">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">

                    <label class="col-md-4">Email</label>
                    <div class="row-cols-2">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4">Password</label>
                    <div class="row-cols-2">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4">Phone number</label>
                    <div class="row-cols-2">
                        @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-4">Aadhar number</label>
                    <div class="row-cols-2">
                        @Html.EditorFor(model => model.AadharNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AadharNumber, "", new { @class = "text-danger" })
                    </div>
                </div>


                <br>
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Save changes" class="btn btn-default" />
                    </div>
                </div>
                <button class="btn btn-md btn-info" id="btn" onclick="location.href = '@Url.Action("IndexRenter","Account")'">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    Back
                </button>
            </div>
        </div>
       

    }     
    <img src="~/Icons/logo.png" class="logo" />

          
</body>